### ISSUE TITLE
Measurement + Reset

### ISSUE THREAD

**Issue by trevormccrt** [quantumlib/Cirq#1454] opened 2019-03-21 17:14 UTC
It would be great if the simulator had a way to measure in the middle of the circuit and reset the qubit to some known state (|0>?), allowing that qubit to be used for something else for further operations.

**Comment by Strilanc** [comment] 2019-03-21 23:08
Duplicate of https://github.com/quantumlib/Cirq/issues/1452

**Closed by Strilanc** 2019-03-21 23:08 UTC
