### ISSUE TITLE
CI run of pytest fails to set up python environment

### ISSUE THREAD

**Issue by wcourtney** [quantumlib/Cirq#6789] opened 2024-11-08 18:52 UTC
**Description of the issue**
In my PR, the "Pytest MacOS (3.10)" job fails at the "Set up Python environment" step:
```
  Error: WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
  Error: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
  Error: WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
  Error: WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
  Error: WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
  Error: WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
  Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Error: ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
  ERROR: No matching distribution found for pip
  Error: The process '/bin/bash' failed with exit code 1
```

**How to reproduce the issue**

You can view an example failure at https://github.com/quantumlib/Cirq/actions/runs/11747706827/job/32730192696?pr=6786#annotation:3:9564

**Comment by dv8081** [comment] 2024-11-11 08:05
Hi @wcourtney i noticed this issue is due to an SSL module error, and I’m confident I can fix it by setting up Python with SSL support. Could you please assign this task to me?

**Comment by pavoljuhas** [comment] 2024-11-12 20:57
@wcourtney - the current invocations of that job pass the "Set up Python environment" step, for example,
https://github.com/quantumlib/Cirq/actions/runs/11804458273/job/32888026295?pr=6790

Do you still experience the problem or should we close assuming a transient error on the GitHub side?

**Comment by pavoljuhas** [comment] 2024-11-13 18:22
will do last check with @wcourtney and then close.

**Comment by pavoljuhas** [comment] 2024-11-13 18:54
Closing - not reproducible.  Please reopen if this happens again.

**Closed by pavoljuhas** 2024-11-13 18:54 UTC
Labels: kind/bug-report, triage/needs-more-evidence
