### ISSUE TITLE
Wrong simulator in Hello QBit example

### ISSUE THREAD

**Issue by rdisipio** [quantumlib/Cirq#1206] opened 2018-11-29 19:41 UTC
Hi,

  the example that appears in the README file does not work. I get the following error:

```
Circuit:
(0, 0): ───X^0.5───M('m')───
Traceback (most recent call last):
  File "./quick_test.py", line 15, in <module>
    simulator = cirq.Simulator()
AttributeError: module 'cirq' has no attribute 'Simulator'
```

It works fine if I just change the line where you define the simulator with:

```
simulator = cirq.google.XmonSimulator()
```

Cheers,
Riccardo

**Comment by vtomole** [comment] 2018-11-29 20:06
Thanks for opening up this issue @rdisipio. The example in the README works for me based on the latest code from the master branch. Could you please emphasize why that example is not working for you? Are you receiving an error message? Is so, what is the message? Are you receiving incorrect output?

**Comment by rdisipio** [comment] 2018-11-29 20:19
Hi,

   I think I just followed the instructions. I created a virtualenv based on python3 and 
```
pip install Cirq
```

Then I just tried to execute the code, but I got this error:

```
Circuit:
(0, 0): ───X^0.5───M('m')───
Traceback (most recent call last):
  File "./quick_test.py", line 15, in <module>
    simulator = cirq.Simulator()
AttributeError: module 'cirq' has no attribute 'Simulator'
```

As reported, by changing the line where the simulator is defined, I can make it work. Perhaps I should check out the master branch instead? Is it available from pip already? Or do I have to clone the repository?

Thanks,
Riccardo

**Comment by Ashalynd** [comment] 2018-11-29 20:37
I confirm. Could reproduce this from the version installed with pip (python3).

**Comment by Ashalynd** [comment] 2018-11-29 20:40
`pip freeze | grep cirq` 
`cirq==0.2.dev0`

**Comment by rdisipio** [comment] 2018-11-29 20:43
Hi, 

  I clone the repository from git, and now it worked fine with the ```cirq.Simulator()``` simulator. Perhaps you want to make it more explicit in the REAME file. 

Thanks!
Riccardo

**Comment by Ashalynd** [comment] 2018-11-29 20:45
Suggestion: add release notes somewhere. ( I couldn't find an easy way to figure out what version of Cirq has been released to be installed via pip. )

**Comment by vtomole** [comment] 2018-11-29 20:56
@rdisipio  All the examples on the master branch are up to date with the version on master; no need to add anything to that. The problem arises from different versions of Cirq where each version might no be backwards compatible.

**Comment by Ashalynd** [comment] 2018-11-30 10:54
Yep, pip install cirq --upgrade solves this issue.
(Verified that it ups Cirq to 0.4.0)

**Comment by kevinsung** [comment] 2018-11-30 18:05
This issue is really about the README on GitHub potentially being out of sync with the PyPI version, which can cause confusion.

**Comment by Strilanc** [comment] 2018-11-30 18:40
We should be careful about documentation saying `pip install cirq` and then using dev-version code. And if the readme contains dev-version code, we should probably call that out with bold text. I've been assuming that non-dev-using users go to readthedocs and dev-using users go to github, but that's not a very good approximation.

**Comment by rdisipio** [comment] 2018-11-30 18:42
Hi,

  I think the problem is that there are some articles and blog post around that point to the GitHub repository. Hence, I tried to follow the instructions that appear in that README file, not from readthedocs. 

Best,
Riccardo

**Comment by vtomole** [comment] 2018-11-30 18:57
In my opinion, the README should not have dev-version code because the README links to the install instructions that say "use `pip install cirq`". If the README said

```
git clone git@github.com:quantumlib/Cirq.git
cd Cirq
pip install -e .
```
That would be another story.

**Comment by Strilanc** [comment] 2018-12-04 08:47
`pip freeze | grep cirq` will tell you the installed version

I will close this issue because the disagreement between the readme and the released version is resolved. I'll keep this in mind when changing the readme in the future.

**Closed by Strilanc** 2018-12-04 08:47 UTC
