### ISSUE TITLE
ASCII Formatting Issues

### ISSUE THREAD

**Issue by ldabas** [quantumlib/Cirq#3999] opened 2021-04-06 18:32 UTC
**Description of the issue**
ASCII Art explaining quantum circuits is misformatted in Intro.ipynb  notebook for introduction to Cirq.
**How to reproduce the issue**
This issue is found on computers that use Japanese as the system language.

<details>

The introduction to Cirq ipynb notebook describes quantum circuits using ASCII art, however, all the ASCII art is moved to the right and mis-formatted for me.

</details>

**Comment by balopat** [comment] 2021-04-07 19:02
Thanks for opening! Closing as dupe of https://github.com/quantumlib/Cirq/issues/3998.

**Closed by balopat** 2021-04-07 19:02 UTC
Labels: kind/bug-report
