### ISSUE TITLE
Add more support for sympy

### ISSUE THREAD

**Issue by cjcarey** [quantumlib/Cirq#2219] opened 2019-09-27 03:55 UTC
Refer to: https://github.com/quantumlib/Cirq/issues/2014 for more details

https://github.com/quantumlib/Cirq/blob/fa5858e61da2d9fabe124ecbdc424a0a608bafe4/cirq/protocols/json.py#L198

**Comment by mpharrigan** [comment] 2019-10-10 17:03
duplicate of #2014

**Closed by mpharrigan** 2019-10-10 17:03 UTC
