### ISSUE TITLE
Can't instantiate abstract class TwoQubitCompilationTargetGateset with abstract method _decompose_two_qubit_operation

### ISSUE THREAD

**Issue by dikoling** [quantumlib/Cirq#6044] opened 2023-03-21 09:52 UTC
**Description of the issue**

Traceback (most recent call last):
  File "/home/ling/compiler_test/cirq_test/demo3.py", line 14, in <module>
    main()
  File "/home/ling/compiler_test/cirq_test/demo3.py", line 10, in main
    gateset = TwoQubitCompilationTargetGateset()
TypeError: Can't instantiate abstract class TwoQubitCompilationTargetGateset with abstract method _decompose_two_qubit_operation

```

put code in code blocks *like this*

def main():
    f = open("./multiplier_n25.qasm")
    arg = f.read()
    f.close()
    circuit = circuit_from_qasm(arg)
    gateset = TwoQubitCompilationTargetGateset()
    circ = cirq.optimize_for_target_gateset(circuit,gateset=gateset)



**Cirq version**
cirq:1.1.0

Why this error, how to solve it?

**Comment by tanujkhattar** [comment] 2023-03-21 21:39
Hi [dikoling](https://github.com/dikoling), thanks for opening the issue! This is working as intended because `TwoQubitCompilationTargetGateset` is meant to be an abstract base class which users derive from and override specific methods that convey the compiler how to compile circuits for specific target gatesets. As an example, look at 

https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/transformers/target_gatesets/cz_gateset.py
https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/transformers/target_gatesets/sqrt_iswap_gateset.py

Both of the files above defined concrete derived classes from `TwoQubitCompilationTargetGateset` for `CZ` and `Sqrt-ISwap` target gatesets. 

I'll close the issue but please let me know if you have any further questions.

**Closed by tanujkhattar** 2023-03-21 21:39 UTC
Labels: kind/bug-report, triage/wont-fix
