### ISSUE TITLE
cg.optimized_for_sycamore removes cirq.WaitGate

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#3289] opened 2020-09-02 15:51 UTC
See title. If you construct a circuit containing wait gates and pass through `cirq.google.optimized_for_sycamore` it removes the delays!

**Comment by balopat** [comment] 2020-09-03 00:15
Thanks for filing - this really looks like a bug. 

**** community note **** 
If someone wants to pick this up from the community, this gives the opportunity to learn about the sycamore optimizer, the idea of gate sets, decomposition and the wait gate.

**Comment by BillGatesNephew** [comment] 2020-12-02 18:48
@balopat  So I did some digging and it looks like this bug is happening because the function `_rewrite()` in `merge_single_qubit_gates.py` takes the product of all unitaries for **all** operations to generate the matrix it then passes to the provided `synthesizer`. I.e.:
```python
unitary = linalg.dot(*(protocols.unitary(op) for op in operations[::-1]))
# Custom synthesizer?
if self._synthesizer is not None:
    return self._synthesizer(q, unitary)
```
 Because `protocols.unitary()` for a wait operation returns the identity matrix, the wait operation effectively gets erased by this. It looks like what you could do here could be either one of two things: 

1. Call the `synthesizer` function for each unitary representing a consecutive sequence of operations that aren't wait operations, and then return the result of these functions with the wait operations inserted appropriately between the optimized single gates for each sequence. 
2. Move all the wait operations to the end of the sequence of single qubit operations, optimize all the single qubit operations together, and then combine all the wait operations into one single wait operation.

I would guess you'd want to do the first option, but it might make sense to add a parameter to `MergeSingleQubitGates` specifying which strategy to use.

**Comment by BillGatesNephew** [comment] 2020-12-04 17:25
After thinking about this a little more. A solution on this might want to do something with `Tag`s. It doesn't seem outside the realm of possibility that you may want to preserve particular individual operations, or sub-circuits  for future `CircuitOperation`s, when optimizing that aren't just `cirq.WaitGate` operations. There maybe could be a `NonOptimizableTag` or something that optimizers check for to avoid optimizing such operations.

**Comment by balopat** [comment] 2021-02-04 00:29
@BillGatesNephew - thanks for jumping on this! I dug in too a bit - in fact there are 3 places where the WaitGate gets killed: 

1. yes, `MergeSingleQubitGates` is one part of the problem - not sure I'd go down the tagging way, because that changes the type of the class unfortunately. We have to think of that design a bit more - that's the thorny part.
2. The other is that none of the xmon, xmon_partial_cz, sqrt_iswap and sycamore optimizers have WaitGate defined as a native gate so they optimize it away. This should be a simple to fix, we should just add WaitGate to the corresponding lists (they are in different places from each other - one day we'll have a nice concept of GateSets https://github.com/quantumlib/Cirq/issues/3243)
3. The DropNegligible optimizer also drops the wait gate - this will need a similar solution to 1.)

Options for 1 and 3: 

1. introduce a configurable set of "protected" gates (NonOptimizable, as you said) - Maybe we could put this into PointOptimizer? The problem is that DropNegligible doesn't inherit from PointOptimizer
2. hard-code WaitGate specific logic - could be viable if we think there's not going to be that many of these...but I have a feeling that we'd prefer 1. even if WaitGate will be the only one for a long time

**Comment by 95-martin-orion** [comment] 2022-03-28 20:32
@tanujkhattar did this survive the transition to Transformers?

**Comment by tanujkhattar** [comment] 2022-05-05 18:57
The recommended method now for optimizing circuits for the sycamore back-end is `cirq.optimize_for_target_gateset(circuit, gateset=cg.SycamoreTargetGateset(), context=context)`

The new method supports tagging operations (like wait gates) with a no-compile tag and specifying the no-compile tags in the transformer context. Operations marked with `context.tags_to_ignore` will not be compiled (and hence removed) by the optimizer. 

I will go ahead and close this issue. Please reopen if you the recommended features are not enough.

**Closed by tanujkhattar** 2022-05-05 18:57 UTC
Labels: triage/discuss, kind/bug-report, triage/accepted, area/decompose, area/google, area/transformers, complexity/low, skill-level/advanced, good for learning, area/google/optimizers, time/before-1.0

**Comment by mpharrigan** [comment] 2022-05-06 20:27
but shouldn't WaitGate be part of the sycamoretargetgateset? It's a gate we can do on sycamore
