### ISSUE TITLE
Make OS specific dev install instructions

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1347] opened 2019-02-04 19:45 UTC
Currently we assume a unix environment https://cirq.readthedocs.io/en/stable/development.html

**Comment by Strilanc** [comment] 2019-02-04 19:47
We should also try to simplify the install, e.g. not depend on virtualenvwrapper and use a similar process to openfermioncirq where we leverage pip's -e argument.

**Comment by dabacon** [comment] 2020-05-03 18:36
Do we have a handle on how these install instructions should differ?

I think we already recommend using `pip -e` in recommendations.

**Comment by balopat** [comment] 2020-09-22 14:09
Duplicate of #1121.

**Closed by balopat** 2020-09-22 14:09 UTC
Labels: kind/docs, triage/duplicate
