### ISSUE TITLE
 'cirq.sim.simulator' 

### ISSUE THREAD

**Issue by sassan72** [quantumlib/Cirq#4189] opened 2021-06-11 15:42 UTC
'cirq.sim.simulator' has no attribute 'SimulatesExpectationValues'.

How to solve this problem?

**Comment by vtomole** [comment] 2021-06-11 16:07
Hey @sassan72, please paste a snippet of the program that throws this error so that we may reproduce it.

**Comment by sassan72** [comment] 2021-06-16 15:52
example of page 7 of Quantum TensorFlow paper: https://arxiv.org/pdf/2003.02989.pdf.

**Comment by sassan72** [comment] 2021-06-16 15:52
qubit = cirq . GridQubit (0 , 0)
theta = sympy . Symbol (’theta ’)
c = cirq . Circuit ( cirq .X ( qubit ) ** theta )
c_tensor = tfq . convert_to_tensor ([ c] * 3)
theta_values = tf . constant ([[0] ,[1] ,[2]])
m = cirq . Z( qubit )
paulis = tfq . convert_to_tensor ([ m ] * 3)
expectation_op = tfq . get_expectation_op ()
output = expectation_op (
c_tensor , [’theta ’], theta_values , paulis )
abs_output = tf . math . abs ( output )

**Comment by vtomole** [comment] 2021-06-16 19:33
I don't get your error. I don't get a different error: `tensorflow.python.framework.errors_impl.InvalidArgumentError: pauli_sums must be rank 2. Got rank 1. [Op:TfqSimulateExpectation]
`

```python
import cirq
import sympy
import tensorflow as tf
import tensorflow_quantum as tfq

qubit = cirq.GridQubit(0 , 0)
theta = sympy.Symbol('theta')
c = cirq.Circuit(cirq.X(qubit) ** theta)
c_tensor = tfq.convert_to_tensor ([c] * 3)
theta_values = tf.constant ([[0] ,[1] ,[2]])
m = cirq.Z(qubit)
paulis = tfq.convert_to_tensor ([m] * 3)
expectation_op = tfq.get_expectation_op ()
output = expectation_op (c_tensor , ['theta'], theta_values , paulis )
abs_output = tf.math.abs(output)
```

```
Traceback (most recent call last):
  File "test.py", line 65, in <module>
    output = expectation_op (c_tensor , ['theta'], theta_values , paulis )
  File "/home/vtomole/venv/lib/python3.8/site-packages/tensorflow_quantum/core/ops/circuit_execution_ops.py", line 135, in <lambda>
    op(programs, symbol_names, symbol_values, pauli_sums)
  File "/home/vtomole/venv/lib/python3.8/site-packages/tensorflow_quantum/core/ops/tfq_simulate_ops.py", line 44, in tfq_simulate_expectation
    return SIM_OP_MODULE.tfq_simulate_expectation(
  File "<string>", line 51, in tfq_simulate_expectation
  File "<string>", line 103, in tfq_simulate_expectation_eager_fallback
  File "/home/vtomole/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: pauli_sums must be rank 2. Got rank 1. [Op:TfqSimulateExpectation]

```


```
cirq version: 0.11.0
tensorflow version: 2.4.1
tensorflow-quantum version: 0.5.1
```

**Comment by MichaelBroughton** [comment] 2021-06-16 20:58
Thanks @vtomole . The error you are getting is what *should* be happening in your snippet. This is a mistake in the whitepaper that we will fix in the v2 which should be coming in the next few months. The fix is to ensure the the `paulis` tensor is rank 2 instead of rank1. You could do this by adding another list dimension to it before converting it to a tensor.

I'm going to go ahead and close this for now since this isn't a problem with Cirq it's a problem with TFQ. @sassan72 would you mind re-opening this issue on the [TFQ github](https://github.com/tensorflow/quantum/issues) with a small snippet of code that can reproduce the error you are seeing (if it is different from the one Victory got) along with the version of Cirq + TFQ you are using ?

**Closed by MichaelBroughton** 2021-06-16 20:58 UTC
Labels: area/simulation, kind/bug-report, triage/needs-more-evidence
