### ISSUE TITLE
TrialResults seems to assume only boolean results

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#3002] opened 2020-05-13 18:59 UTC
Documentation says this but we think it should work for three outcome or more measurements.  

We should

1.  verify it works for >2 dimensional outcomes
2. update doc strings

**Comment by kevinsung** [comment] 2020-05-13 19:41
This at least will need to be changed:
https://github.com/quantumlib/Cirq/blob/3d645b7ec08d05d8bbd7f7461b717bba865e362a/cirq/study/trial_result.py#L111

**Comment by cduck** [comment] 2020-05-13 20:13
Workaround: Use `sampler.run().measurements` instead of `sampler.run().data` or `sampler.sample()` until this is fixed.

This looks like something I missed (I even reviewed the PR that added `TrialResult.data`).  The issue is `TrialResult.data`, `TrialResult.histogram`, `TrialResult.multi_measurement_histogram`, and `TrialResults._json_dict_` all convert `TrialResults.mreasurements` to all assume binary measurements when converting the `mesaurements` dictionary to another form.

Here's an example:
```python
import numpy as np
import cirq

class PlusOneGate(cirq.SingleQubitGate):
    def _qid_shape_(self):
        return (3,)
    def _unitary_(self):
        return np.array([[0, 0, 1],
                         [1, 0, 0],
                         [0, 1, 0]])
    def _circuit_diagram_info_(self, args):
        return '[+1%3]'
PlusOne = PlusOneGate()

q = cirq.LineQid.range(4, dimension=3)
c = cirq.Circuit(
    PlusOne.on_each(*q),
    PlusOne.on_each(q[0], q[2]),
    cirq.measure(q[0], key='a'),
    cirq.measure(*q[1:], key='b'),
)
print(c)
#0 (d=3): ───[+1%3]───[+1%3]───M('a')───
#
#1 (d=3): ───[+1%3]────────────M('b')───
#                              │
#2 (d=3): ───[+1%3]───[+1%3]───M────────
#                              │
#3 (d=3): ───[+1%3]────────────M────────

samp = cirq.Simulator()
results = samp.run(c, repetitions=2)

print(results.measurements)
# Correst qutrit measurements:
#{'a': array([[2],
#       [2]], dtype=uint8), 'b': array([[1, 2, 1],
#       [1, 2, 1]], dtype=uint8)}

print(results.data)
print(samp.sample(c, repetitions=2))  # Same as samp.run().data
# Incorrect when converted to a data frame:
#   a  b
#0  1  7
#1  1  7

print(results.histogram(key='b'))
# Incorrect generated histogram:
# Counter({7: 2})
```

**Comment by cduck** [comment] 2020-05-13 20:18
Currently, `TrialResult` doesn't know the qid shape of its data so these methods can't do the right thing.  To fix this, it needs to store a qid shape (a tuple of qubit dimensions: Tuple[int, ...]) for each measurement key and every sampler that supports qudits needs to specify the shapes when they create `TrialResults`.

**Comment by maffoo** [comment] 2020-05-13 20:29
Instead of storing the qid shapes in TrialResult, I'd suggest we just store the list of qid's themselves. These will include the shapes, of course, but this also makes TrialResult more self-documenting since you can interpret the measurements without referring back to the measurement gate in the circuit to know what qubits were measured.

**Comment by smitsanghavi** [comment] 2020-05-13 21:53
FWIW, this concern was raised in the original PR and it was assumed that TrialResult has access to the qid shape https://github.com/quantumlib/Cirq/pull/1811#issuecomment-511067677.

+1 to including the qids themselves in TrialResult.

**Comment by kevinsung** [comment] 2020-05-14 04:42
@cduck Actually the JSON serialization does support qudits. For instance, adding
```python
assert cirq.read_json(json_text=cirq.to_json(results)) == results
```
to the end of your example works.

**Comment by cduck** [comment] 2020-05-14 14:12
You are right @kevinsung.  I missed that `_json_dict_` checks if any measurement result values are not 0/1 and uses numpy's array serialization instead.

**Comment by 95-martin-orion** [comment] 2022-03-28 20:40
Hey @daxfohl, did #4781 end up resolving this?

**Comment by daxfohl** [comment] 2022-03-28 20:55
Yes. That gets passed in from the `OperationTarget.log_of_measurement_results` property, which uses `get_digits`, which is integral not boolean. https://github.com/quantumlib/Cirq/blob/9fd5af14d1fea2ea702c628834230f9611425523/cirq-core/cirq/sim/operation_target.py#L91

**Closed** 2022-03-28 21:22 UTC
Labels: kind/feature-request, triage/accepted, area/result, complexity/medium, area/qudits, skill-level/advanced, good for learning, time/before-1.0
