### ISSUE TITLE
Run methods in Engine and simulators should fail fast if there are no measurements.

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#485] opened 2018-06-20 02:02 UTC

**Comment by dabacon** [comment] 2019-08-23 16:54
All run methods so do this check.

**Comment by tanujkhattar** [comment] 2024-01-31 01:07
This can be closed now. Duplicate of https://github.com/quantumlib/Cirq/issues/1519

**Closed by tanujkhattar** 2024-01-31 01:07 UTC
Labels: kind/feature-request, triage/accepted, area/simulation, area/samplers, area/google/engine, priority/p3
