### ISSUE TITLE
Channels should support keys for labeling outcomes during simulations

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1357] opened 2019-02-07 18:22 UTC
there should be a way to get results out during simulation

**Comment by dabacon** [comment] 2019-02-15 22:22
Adding _measurement_key_ protocol.

**Comment by dabacon** [comment] 2020-05-03 18:40
There is a concrete proposal to move to a protocol `_acts_on_` and this would be fixed as part of this.

**Comment by 95-martin-orion** [comment] 2020-12-03 00:14
Absorbing into #3566 to capture more recent discussion.

**Comment by 95-martin-orion** [comment] 2020-12-03 00:15
Duplicate of #3566

**Closed by 95-martin-orion** 2020-12-03 00:15 UTC
Labels: area/channels, area/measurements, kind/feature-request, triage/accepted
