### ISSUE TITLE
circuit_to_latex_using_qcircuit converts RotXGate to \targ

### ISSUE THREAD

**Issue by askolik** [quantumlib/Cirq#1046] opened 2018-10-24 14:43 UTC
When a circuit contains RotXGates, cirq.contrib.qcircuit.qcircuit_diagram.circuit_to_latex_using_qcircuit converts those to target qubit symbol `\targ` in the LaTeX output instead of `\gate{\text{X}}`.

Example:

```
circuit = cirq.Circuit()
circuit.append(RotXGate()(0))
circuit.append(RotXGate()(1))
circuit.append(RotXGate()(2))
circuit.append(RotXGate()(3))
circuit.append(RotZGate()(0))
circuit.append(RotZGate()(1))
circuit.append(RotZGate()(2))
circuit.append(RotZGate()(3))
```

```
0: ───X───────────────Z───────────────

1: ───────X───────────────Z───────────

2: ───────────X───────────────Z───────

3: ───────────────X───────────────Z───
```

Produces following LaTeX:

```
\Qcircuit @R=1em @C=0.75em { \\ 
 \lstick{\text{0}}& \qw & \targ \qw &\qw &\qw &\qw & \gate{\text{Z}} \qw &\qw &\qw &\qw &\qw\\
 \lstick{\text{1}}& \qw &\qw & \targ \qw &\qw &\qw &\qw & \gate{\text{Z}} \qw &\qw &\qw &\qw\\
 \lstick{\text{2}}& \qw &\qw &\qw & \targ \qw &\qw &\qw &\qw & \gate{\text{Z}} \qw &\qw &\qw\\
 \lstick{\text{3}}& \qw &\qw &\qw &\qw & \targ \qw &\qw &\qw &\qw & \gate{\text{Z}} \qw &\qw \\ 
 \\ }
```

Which renders as:

![x_to_target](https://user-images.githubusercontent.com/35702116/47438584-0e0e5580-d7ab-11e8-9650-ec9def0dd73b.png)

**Comment by Strilanc** [comment] 2018-10-24 20:32
This is intentional. The X gate is the NOT gate, so we draw it as a NOT gate.

(We'd do it in text diagrams too, if it weren't so common for supposedly fixed-width fonts to make '⊕' too wide and skew the diagram.)

Is there a reason you specifically want it to draw as an X?

**Comment by askolik** [comment] 2018-10-25 08:37
I see. I was thinking in terms of parameterized rotations, and wanted to generate a diagram for something like this:

```
circuit = cirq.Circuit()

circuit.append(RotXGate(half_turns=0.5)(0), strategy=InsertStrategy.EARLIEST)
circuit.append(RotZGate(half_turns=1)(1), strategy=InsertStrategy.EARLIEST)
circuit.append(RotXGate(half_turns=1)(2), strategy=InsertStrategy.EARLIEST)

circuit.append(RotXGate(half_turns=0.2)(0), strategy=InsertStrategy.EARLIEST)
circuit.append(RotZGate(half_turns=0.1)(1), strategy=InsertStrategy.EARLIEST)
circuit.append(RotXGate(half_turns=0.4)(2), strategy=InsertStrategy.EARLIEST)

circuit.append(RotXGate(half_turns=1)(0), strategy=InsertStrategy.EARLIEST)
circuit.append(RotZGate(half_turns=1)(1), strategy=InsertStrategy.EARLIEST)
circuit.append(RotXGate(half_turns=1)(2), strategy=InsertStrategy.EARLIEST)
```
```
0: ───X^0.5───X^0.2───X───

1: ───Z───────Z^0.1───Z───

2: ───X───────X^0.4───X───
```

In LaTeX this looks like this:

![parameterized](https://user-images.githubusercontent.com/35702116/47486535-dce06480-d840-11e8-9afe-83dac62d742f.png)

It threw me off that the X Gate renders differently depending on the value of half_turns, in this scenario I would prefer having the X symbol everywhere for clarity.

**Comment by Strilanc** [comment] 2018-10-25 09:03
I see...

You can work around the issue by creating a custom gate `MyX` that inherits `RotXGate` but also `cirq.contrib.qcircuit.QCircuitDiagrammable`. Then use `MyX` instead of `cirq.X`.

```python
class MyX(cirq.RotXGate, cirq.contrib.qcircuit.QCircuitDiagrammable):
    def qcircuit_diagram_info(args):
        return ___WHATEVER_YOU_LIKE___
```

I think that the current behavior is the one we want, at least for now, and there is a workaround you can use, so I will close this issue as 'working as intended'.

**Closed by Strilanc** 2018-10-25 09:03 UTC

**Comment by askolik** [comment] 2018-10-25 09:41
Thanks for the workaround!
