### ISSUE TITLE
Remove IdentityOperation

### ISSUE THREAD

**Issue by peterse** [quantumlib/Cirq#2520] opened 2019-11-09 20:37 UTC
At some point it became harder to work with the typing of `cirq.I`, for example:
```
>>> circuit = cirq.Circuit(cirq.I(q0))
>>> list(circuit.findall_operations_with_gate_type(cirq.IdentityGate))
[]
>>> list(circuit.findall_operations_with_gate_type(cirq.IdentityOperation))
[]
```
This is confusing behavior. Possibly related issues: #2517 #2515 

EDIT: `circuit.findall_operations_with_gate_type(cirq.IdentityGate)` now behaves as expected  case as of #2515 but the better solution is to remove `IdentityOperation` entirely

**Comment by Strilanc** [comment] 2019-11-11 22:24
The root cause here is a historical accident where we introduced `IdentityOperation` before `IdentityGate`. It can be fixed by adding a `gate` attribute to `IdentityOperation` that returns an `IdentityGate` instance. It can also be fixed by deleting `IdentityOperation`, which is strictly redundant at this point and so that's probably the better approach.

**Comment by peterse** [comment] 2019-11-13 04:24
Ah that makes sense; #2515 fixed the above but I agree that removing `IdentityOperation` is a better and simplifying solution

**Comment by vtomole** [comment] 2019-12-13 19:05
This has been deprecated. I think @Strilanc removes deprecated functions during a release so I'll close this.

**Closed by vtomole** 2019-12-13 19:05 UTC
