### ISSUE TITLE
Raising PauliSum to integer power gives incorrect results

### ISSUE THREAD

**Issue by sergeisakov** [quantumlib/Cirq#6017] opened 2023-02-22 19:47 UTC
**Description of the issue**
Raising PauliSum to the third power or greater gives incorrect results. It seems this can be fixed by replacing line 844 in https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/ops/linear_combinations.py with `base *= self`.

**How to reproduce the issue**
```
import cirq

n = 4
o = sum(cirq.Z(cirq.LineQubit(q)) for q in range(n))
assert(o * o * o == o**3)
```

**Cirq version**
1.1.0

**Comment by eliottrosenberg** [comment] 2023-02-22 20:18
Causes https://github.com/quantumlib/Cirq/issues/6011

**Comment by mustapha-saad-codeStar** [comment] 2023-02-28 07:42
Hi @tanujkhattar, I would love to work on this issue. Please, what are the deliverables?

**Comment by tanujkhattar** [comment] 2023-02-28 18:34
@codeStar Thanks for expressing your interest! This issue is already taken, so I'd recommend you to look at https://github.com/quantumlib/Cirq/issues/5999 instead.

**Comment by mustapha-saad-codeStar** [comment] 2023-03-01 06:11
No worries man, all good. If the issue is still open, you can tag me and I would be glad to help fix it...

**Comment by pavoljuhas** [comment] 2023-03-23 04:50
Fixed by #6019

**Closed by pavoljuhas** 2023-03-23 04:50 UTC
Labels: good first issue, no QC knowledge needed, kind/bug-report, triage/accepted, area/paulis
