### ISSUE TITLE
Extend the Sampler API 

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3148] opened 2020-07-18 13:50 UTC
From @mpharrigan: "Embolden the Sampler API so you can do everything with it. For example, batching should be added to the Sampler API. You should be able to modify your code to use batching (and test it) without a QPU reservation"

**Comment by thanacles** [comment] 2021-07-04 19:59
@balopat @zaqqwerty I feel like this issue is a duplicate of: https://github.com/quantumlib/Cirq/issues/3224 . Is there something I'm missing?

**Comment by mpharrigan** [comment] 2021-07-07 07:41
Sure, closing as duplicate

**Closed by mpharrigan** 2021-07-07 07:41 UTC
Labels: area/google, complexity/medium, kind/feature-request, triage/accepted
