### ISSUE TITLE
Glitched Circuit Diagram after flatten

### ISSUE THREAD

**Issue by AlkaidCheng** [quantumlib/Cirq#3196] opened 2020-08-06 07:12 UTC
**Description of the issue**
When a circuit has a parameterised gate as a product of symbols, flattening the circuit will produce a glitched circuit diagram where the parameterised expression is gone. This will further affect the circuit diagram if two qubit gates are also present in the circuit. 
**How to reproduce the issue**

```
import sympy as sp
from cirq import CNOT, rz, Circuit
cq = cirq.Circuit()
qubits = cirq.GridQubit.rect(2,1)
x = sp.symarray('x', 2)
cq.append([rz(x[0]*x[1])(qubits[-1]), CNOT(*tuple(qubits))])
new_cq, _= cirq.flatten(cq)
new_cq
```
This will product circuit diagram like this

This will product circuit diagram like this

(0, 0): ─────────────────────────@───
　　　　　　　　　　　│
(1, 0): ───Rz(pi*)───X───

**Cirq version**
0.8.2

**Comment by balopat** [comment] 2020-08-06 22:10
Hi @AlkaidCheng  - the result on the CLI is 

```
(0, 0): ─────────────────────────@───
                                 │
(1, 0): ───Rz(pi*<x_0*x_1/pi>)───X───

```

I'm guessing that the angle brackets `<` `>` create the problem in a browser for you - maybe Jupyter notebooks?

**Comment by balopat** [comment] 2020-08-06 22:17
Yeah I just confirmed that that's the issue. In Jupyter notebooks this shows up incorrectly, but only if the object is returned as the result of the cell - if you use print, it works
```
print(new_cq)
```
Gives a workaround, but it might be a bit annoying. Not sure yet what the right solution is here.

**Comment by AlkaidCheng** [comment] 2020-08-07 03:20
Right, I was using Colab notebooks and doing print will solve the problem.

**Comment by AlkaidCheng** [comment] 2020-08-07 03:27
I have been using the circuit is returned as the result of the cell for printing circuits because for jupyter notebooks, doing print(circuit) will mess up the diagram by introducing extra newlines if the circuit is too long. Interestingly doing print(circuit) in Colab notebooks does not have this problem.

**Comment by balopat** [comment] 2020-08-13 00:03
For someone who wants to look at this should review the possibility of replacing `<>` angle brackets with another pair of symbols (e.g. `{}` or `[]`) here: https://github.com/quantumlib/Cirq/blob/master/cirq/study/flatten_expressions.py

**Comment by abhik-99** [comment] 2020-08-13 18:06
Hey! Can I contribute to this issue?

**Comment by balopat** [comment] 2020-08-13 20:24
Hi @abhik-99 - yes please, feel free to grab it!

**Comment by balopat** [comment] 2020-08-13 20:47
After a quick internal chat - consensus is on using `[ ]`.

**Comment by cduck** [comment] 2020-08-13 20:52
I haven't been following this issue but it sounds like the angle brackets are a problem in the Jupyter scrollable view because they are interpreted as HTML tags.  An easy fix for this would be to the builtin `html` module to escape any special characters in `_repr_html_` for `Circuit`.

**Comment by balopat** [comment] 2020-08-13 21:00
Oooo awesome suggestion @cduck, I didn't know about `_repr_html_` - @abhik-99 - please try that out - if we could implement the escaping there that would be even better and actually more robust.

**Comment by abhik-99** [comment] 2020-08-14 00:41
Sure @balopat! On it. Thanks.

**Comment by mpharrigan** [comment] 2020-08-14 03:33
xref #2905 `<virtual>` labels for noise tags also get eaten in jupyter sometimes

**Comment by abhik-99** [comment] 2020-08-15 12:57
So hey @balopat and @cduck I tried out two possible solutions.

1. Replacing the ```< >``` with ```[ ]``` in https://github.com/quantumlib/Cirq/blob/master/cirq/study/flatten_expressions.py in [here](https://drive.google.com/file/d/1NwHgvITmaMHpIEjZuN6Vwq9jJszeABDZ/view?usp=sharing).
2. Trying to escape using the builtin ```html``` module in https://github.com/quantumlib/Cirq/blob/master/cirq/circuits/circuit.py in [here](https://drive.google.com/file/d/1PXxrrZR8Jhs7w0M3E28-Fqed2K1ihpq3/view?usp=sharing).

Solution 1 is the easiest one but solution 2 is better in preventing similar future issues. The thing is that in solution 2, as the ```&lt;``` and ```&gt;``` are being shown as ```<``` and ```>```, there is a space that needs to be filled. Adding in spaces only enlarges the image width-wise. I have tried using ```cirq.circuits._text_diagram_drawer.TextDiagramDrawer,shift()``` but that only shifts the whole diagram not a single qubit line.

Any suggestions?

**Comment by cduck** [comment] 2020-08-15 17:20
It would be helpful to give the code you used for those examples.  I would do the second solution by changing line https://github.com/quantumlib/Cirq/blob/master/cirq/circuits/circuit.py#L378 to `+ html.escape(...)`.  This way circuit diagram will make space for `<` *before* it is replaced with the escape code.

**Comment by abhik-99** [comment] 2020-08-15 18:00
Thanks a lot @cduck ! Just did that and turns out it works great. Opening a PR on a side branch on the lint and tests pass.

**Closed** 2020-08-18 19:22 UTC
Labels: difficulty: low, good first issue, kind/bug-report, triage/accepted
