### ISSUE TITLE
Classical Control: Feedforward

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3232] opened 2020-08-19 04:07 UTC
**Problem:** 

Cirq currently only supports a single unrolled circuit.  Measurements results cannot be fed forward to influence the future execution of the circuit.  This leads to, for example, Cirq not being able to easily describe a teleportation experiment.  There are also use cases for simple feed forward in variational ansatz and simple quantum error correcting protocols.

**Depends on feature:** Classical data (#3231)

**Rough requirements:**

- Define how classical data can influence future execution 
- how is control specified
- what is changed by the result of the control
- support of multiple cases
- Fit in with the specification of data in the Classical Data feature.
- Support serialization of the specification of control and of the action resulting from the control.
-

**Comment by smitsanghavi** [comment] 2020-12-17 00:42
A previous feature request https://github.com/quantumlib/Cirq/issues/762 was closed as intended because we didn't know how the hardware was going to support this. Do we have more idea now? Any specific requirements due to hardware constraints?

**Comment by daxfohl** [comment] 2021-08-17 22:44
@95-martin-orion @smitsanghavi @MichaelBroughton Initial RFC here: https://tinyurl.com/cirq-feedforward. I'm reasonably happy with it as a first draft.

**Closed** 2022-02-07 20:08 UTC
Labels: kind/roadmap-item, area/classical
