### ISSUE TITLE
Failed to import Ansatz

### ISSUE THREAD

**Issue by ChrisW918** [quantumlib/Cirq#4238] opened 2021-06-21 08:22 UTC
I followed the instruction in github to import types of ansatz from _openfermioncirq.varional_ , but it reports the fault:

_ModuleNotFoundError: No module named 'openfermion.ops._givens_rotations'_

I tried to check the _ops_ package, and it turns out that _givens_rotations_ has been removed.

How can I deal with this? Or are there other ways to import ansatz?

**Comment by vtomole** [comment] 2021-06-21 14:34
Hey, @ChrisW918 . This is an OpenFermion issue. I'm going to close it because it's a duplicate of https://github.com/quantumlib/OpenFermion/issues/732.

**Closed by vtomole** 2021-06-21 14:34 UTC
