### ISSUE TITLE
Support OpenQASM 3.0

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#3518] opened 2020-11-20 22:41 UTC
Currently we only support OpenQASM 2.0, we should start to look into what is required for exporting and importing to and from the new version of [OpenQASM 3.0](https://qiskit.github.io/openqasm/)

**What is the urgency from your perspective for this issue? Is it blocking important work?**
P3 - I'm not really blocked by it, it is an idea I'd like to discuss / suggestion based on principle

**Comment by vtomole** [comment] 2021-10-21 16:46
I will close this issue as a duplicate of https://github.com/quantumlib/Cirq/issues/4509 even though this was the first one because the linked issue has more comments.

**Closed by vtomole** 2021-10-21 16:46 UTC
Labels: kind/feature-request, triage/accepted, area/qasm, roadmap-candidate
