### ISSUE TITLE
Different output for the same seed in Simulator?

### ISSUE THREAD

**Issue by ArfatSalman** [quantumlib/Cirq#5986] opened 2023-01-22 23:00 UTC
**Description of the issue**

I'm expecting two equivalent (but different) circuits to give the same the output given the same seed. Are different outputs intended behaviour?

**How to reproduce the issue**

**Circuit 1**
```python
import cirq
qr = [cirq.NamedQubit("q" + str(i)) for i in range(8)]

circuit = cirq.Circuit()

circuit.append((cirq.X.controlled(num_controls=3) ** 0.5)(qr[0], qr[7], qr[6], qr[3]))
circuit.append((cirq.X**0.5)(qr[0]))
circuit.append((cirq.X.controlled() ** 0.5)(qr[0], qr[2]))
circuit.append(cirq.rx(0.7279391018916035).controlled().on(qr[0], qr[3]))

# Measurements
circuit.append(cirq.measure(qr))

simulator = cirq.Simulator(seed=1128889)
result = simulator.run(circuit, repetitions=2771)
result_dict = dict(
    result.multi_measurement_histogram(keys=circuit.all_measurement_key_names())
)
for i in sorted(result_dict):
    print(f"{i} => {result_dict[i]}")

"""
(0,) => 1342
(128,) => 621
(144,) => 109
(160,) => 612
(176,) => 87
"""
```

**Circuit 2**
```python
import cirq


qr = [cirq.NamedQubit("q" + str(i)) for i in range(8)]


circuit = cirq.Circuit()

circuit.append((cirq.X.controlled(num_controls=3) ** 0.5)(qr[0], qr[7], qr[6], qr[3]))
circuit.append((cirq.X**0.5)(qr[0]))

# sub-circuit (an inverted sub-circuit)
# the expectation is that this doesn't affect the circuit output
subcircuit = cirq.Circuit()
subcircuit.append(cirq.CX(qr[5], qr[2]))
subcircuit.append(cirq.CCX(qr[5], qr[3], qr[4]))
circuit.append(subcircuit)
circuit.append(cirq.inverse(subcircuit))
# end sub-circuit

circuit.append((cirq.X.controlled() ** 0.5)(qr[0], qr[2]))
circuit.append(cirq.rx(0.7279391018916035).controlled().on(qr[0], qr[3]))

circuit.append(cirq.measure(qr))


simulator = cirq.Simulator(seed=1128889)
result = simulator.run(circuit, repetitions=2771)
result_dict = dict(
    result.multi_measurement_histogram(keys=circuit.all_measurement_key_names())
)

for i in sorted(result_dict):
    print(f"{i} => {result_dict[i]}")
"""
(0,) => 1342
(128,) => 621
(144,) => 78
(160,) => 643
(176,) => 87
"""
```
<details>

put long logs in details blocks *like this*

</details>

**Cirq version**
You can get the cirq version by printing `cirq.__version__`. From the command line:

```
1.1.0
```

**Comment by tanujkhattar** [comment] 2023-03-01 22:06
This happens because, by default, `cirq.Simulator` has a `split_untangled_states=True` flag set, which tries to optimize the simulation of circuits which can be split into unentangled states. 

In your example, even though the two circuits are equivalent, the second one where you add a subcircuit and it's inverse makes it harder for the simulator to apply this optimization. As a result, for the two cases, the simulation path is different (one has the optimization of splitting unentangled states, other doesn't). This results in different number of calls to the random number generator and therefore a slight variance in the output results. 

To get identical results, you can explicitly turn off this optimization by setting `simulator = cirq.Simulator(seed=1128889, split_untangled_states=False)`. 

Here are the two code snippets that produce identical results by turning off the optimization. 

Circuit-1
```python
In [16]: qr = [cirq.NamedQubit("q" + str(i)) for i in range(8)]
    ...:
    ...: circuit = cirq.Circuit()
    ...:
    ...: circuit.append((cirq.X.controlled(num_controls=3) ** 0.5)(qr[0], qr[7], qr[6], qr[3]))
    ...: circuit.append((cirq.X**0.5)(qr[0]))
    ...: circuit.append((cirq.X.controlled() ** 0.5)(qr[0], qr[2]))
    ...: circuit.append(cirq.rx(0.7279391018916035).controlled().on(qr[0], qr[3]))
    ...:
    ...: # Measurements
    ...: circuit.append(cirq.measure(qr))
    ...:
    ...: simulator = cirq.Simulator(seed=1128889, split_untangled_states=False)
    ...: result = simulator.run(circuit, repetitions=2771)
    ...: result_dict = dict(
    ...:     result.multi_measurement_histogram(keys=circuit.all_measurement_key_names())
    ...: )
    ...: for i in sorted(result_dict):
    ...:     print(f"{i} => {result_dict[i]}")
(0,) => 1342
(128,) => 621
(144,) => 78
(160,) => 643
(176,) => 87
```
Circuit-2
```python
In [31]: qr = [cirq.NamedQubit("q" + str(i)) for i in range(8)]
    ...:
    ...:
    ...: circuit = cirq.Circuit()
    ...:
    ...: circuit.append((cirq.X.controlled(num_controls=3) ** 0.5)(qr[0], qr[7], qr[6], qr[3]))
    ...: circuit.append((cirq.X**0.5)(qr[0]))
    ...:
    ...: # sub-circuit (an inverted sub-circuit)
    ...: # the expectation is that this doesn't affect the circuit output
    ...: subcircuit = cirq.Circuit()
    ...: subcircuit.append(cirq.CX(qr[5], qr[2]))
    ...: subcircuit.append(cirq.CCX(qr[5], qr[3], qr[4]))
    ...: circuit.append(subcircuit)
    ...: circuit.append(cirq.inverse(subcircuit))
    ...: # end sub-circuit
    ...:
    ...: circuit.append((cirq.X.controlled() ** 0.5)(qr[0], qr[2]))
    ...: circuit.append(cirq.rx(0.7279391018916035).controlled().on(qr[0], qr[3]))
    ...:
    ...: circuit.append(cirq.measure(qr))
    ...:
    ...:
    ...: simulator = cirq.Simulator(seed=1128889, split_untangled_states=False)
    ...: result = simulator.run(circuit, repetitions=2771)
    ...: result_dict = dict(
    ...:     result.multi_measurement_histogram(keys=circuit.all_measurement_key_names())
    ...: )
    ...:
    ...: for i in sorted(result_dict):
    ...:     print(f"{i} => {result_dict[i]}")
    ...:
(0,) => 1342
(128,) => 621
(144,) => 78
(160,) => 643
(176,) => 87

```


Since this is intended behavior, I'll go ahead and close the issue.

**Closed by tanujkhattar** 2023-03-01 22:06 UTC
Labels: kind/bug-report, area/simulation, triage/wont-fix
