### ISSUE TITLE
Error when converting a circuit with a Symbol parameter to QASM

### ISSUE THREAD

**Issue by ArfatSalman** [quantumlib/Cirq#5984] opened 2023-01-22 22:00 UTC
**Description of the issue**
When converting this circuit to QASM, I get this error `TypeError: unsupported format string passed to Mod.__format__`

**How to reproduce the issue**

```python
import cirq
from sympy import Symbol
import numpy as np
from cirq.circuits.qasm_output import QasmUGate

p1 = Symbol("p1")

qr = [cirq.NamedQubit("q" + str(i)) for i in range(6)]

circuit = cirq.Circuit()

circuit.append(
    QasmUGate(5.887184334931191 / np.pi, 0.07157463504881167 / np.pi, p1 / np.pi)(qr[5])
)

circuit.append(cirq.measure(qr))

circuit = cirq.resolve_parameters(
    circuit,
    {
        "p1": 2.3864521352475245,
    },
    recursive=True,
)

circuit.to_qasm() # TypeError: unsupported format string passed to Mod.__format__
```

<details>

put long logs in details blocks *like this*

</details>

**Cirq version**
You can get the cirq version by printing `cirq.__version__`. From the command line:

```
1.1.0
```

**Comment by dstrain115** [comment] 2023-02-08 00:44
I think this is actually a new feature, since it has never been supported by the qasm converter.  Leaving it for cirq cync triage.

**Comment by viathor** [comment] 2023-02-23 18:38
Yes, symbolic parameters have never been supported in `QasmUGate`. Still, we should at least make it clear by adding type annotations.

Related: #5985.

**Comment by verult** [comment] 2023-04-12 17:53
From Cirq sync: duplicate of https://github.com/quantumlib/Cirq/issues/5985.

**Closed by verult** 2023-04-12 17:53 UTC
Labels: triage/discuss, kind/bug-report, kind/feature-request, area/gates, area/qasm
