### ISSUE TITLE
Modify automerge script to explain "someone requested changes" case

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#2032] opened 2019-08-27 19:58 UTC
In https://github.com/quantumlib/Cirq/pull/2028#issuecomment-525399478 cirqbot didn't understand that there was an approved review and also a review asking for changes.

**Comment by balopat** [comment] 2020-09-26 13:04
This is a duplicate of #1755.

**Closed by balopat** 2020-09-26 13:04 UTC
Labels: area/cirqbot, complexity/low, kind/bug-report, kind/health, skill-level/beginner, triage/accepted
