### ISSUE TITLE
Add a docstring that summarizes protocols in cirq/protocols/__init__.py

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2888] opened 2020-04-03 23:12 UTC
https://github.com/quantumlib/Cirq/blob/master/cirq/protocols/__init__.py

**Comment by MrSaral** [comment] 2020-04-21 21:35
Can I work on this? I am new around here, is there any slack communication channel?

**Comment by vtomole** [comment] 2020-04-21 22:17
We have a [gitter channel](https://gitter.im/cirqdev).

**Comment by MrSaral** [comment] 2020-04-25 02:07
#2939 Please review

**Comment by balopat** [comment] 2020-08-31 22:44
This is a dupe of https://github.com/quantumlib/Cirq/issues/2973

**Closed by balopat** 2020-08-31 22:44 UTC
Labels: complexity/low, good first issue, kind/docs, triage/accepted
