### ISSUE TITLE
from mpl_toolkits.mplot3d import Axes3D fails for older versions of matplotlib

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#1562] opened 2019-04-24 18:20 UTC
This borks people who don't have a newer matplotlib installation. 

Is it possible to not have this dependency?

**Comment by vtomole** [comment] 2019-04-24 18:55
Which version of `matplotlib` should i use to try to reproduce?

**Comment by vtomole** [comment] 2019-05-05 22:18
@dabacon Ping. Would love an example program that does this too.

**Comment by dstrain115** [comment] 2020-01-15 18:41
I cannot reproduce this with matplotlib down to 2.2.2 (March 2018).  Before that, matplotlib won't install for me due to too many conflicts.

I think this may have been a python2 bug.  Closing this.  We can always re-open if it reoccurs.

**Closed by dstrain115** 2020-01-15 18:41 UTC
