### ISSUE TITLE
Allow PauliString coeffecients to be symbols

### ISSUE THREAD

**Issue by trevormccrt** [quantumlib/Cirq#2260] opened 2019-10-03 04:05 UTC
My goal here is to be able to use the cirq pauli exponentiation interface to compile something like $e^{j \theta X_0 Y_1 + Y_0 X_1 }$ to gates parameterized with the correct symbolic expressions

**Comment by Strilanc** [comment] 2019-10-03 04:54
Makes sense to me that this would be allowed.

**Comment by trevormccrt** [comment] 2019-10-03 06:18
If nobody else objects could you assign this to me?

**Comment by dabacon** [comment] 2020-05-06 23:00
I believe this is a duplicate of #1617.  Going to close this one and move assignment.

**Closed by dabacon** 2020-05-06 23:00 UTC
