### ISSUE TITLE
We have CCX and CNOT but not CCNOT and CX

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1625] opened 2019-05-13 19:22 UTC
We should have both, or at the very least be consistent.

**Comment by vtomole** [comment] 2019-05-13 20:42
I have 

```python
class CXPowGate(CNotPowGate):
    """Another name for CNotPowGate"""
    def __repr__(self):
        if self._global_shift == 0:
            if self._exponent == 1:
                return 'cirq.CX'
            return '(cirq.CX**{})'.format(proper_repr(self._exponent))
        return (
            'cirq.CxPowGate(exponent={}, '
            'global_shift={!r})'
        ).format(proper_repr(self._exponent), self._global_shift)

    def __str__(self) -> str:
        if self._exponent == 1:
            return 'CX'
        return 'Cx**{!r}'.format(self._exponent)
```

```python
CX = CXPowGate()
```

but we could make it 
```python
CX = CNOT
```

Same question with regards to `CCX`; what would be preferred?

**Comment by c-poole** [comment] 2019-05-15 00:55
I don't think we want a duplicate of the PowGate since the users shouldn't be explicitly constructing the gates this way. Instead they should be raising the gate or operation with that gate to the desired power. We should just need CX = CNOT and CCNOT = CCX

**Closed** 2019-05-15 05:21 UTC
