### ISSUE TITLE
Windows build flaky

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#2628] opened 2019-12-06 01:19 UTC
https://travis-ci.com/quantumlib/Cirq/jobs/263688729

Interestingly the failing test is the same as the one at #2468 .

**Comment by KevinVillela** [comment] 2019-12-06 14:36
Is this the same as https://github.com/quantumlib/Cirq/issues/2617? The Travis link you reference above looks like it passed, so I couldn't tell.

**Comment by maffoo** [comment] 2019-12-06 17:22
This looks like a dupe of #2468 to me, so closing. I put up a PR to mark the offending test as xfail so this doesn't block other PRs: #2630.

**Closed by maffoo** 2019-12-06 17:22 UTC
