### ISSUE TITLE
Improved validator for run_batch

### ISSUE THREAD

**Issue by karlunho** [quantumlib/Cirq#3960] opened 2021-03-23 15:28 UTC
When UCLA @ahirthucla was running run_batch against the Google Quantum Computing Service, the service failed several times because of the specific reasons:

- Collisions in the measurment keys
- Too many gates
- Batch sizes being too big

**Describe the solution you'd like**

It would be useful to have a "validate batch" utility function in Cirq to ensure that the batch being created indeed can run.

**[optional] Describe alternatives/workarounds you've considered**

It's not clear if "create_batch_program" does any validation.

**[optional] Additional context (e.g. screenshots)**

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P1 - I need this no later than the next release (end of quarter)

This feature request is in the context of a Teaching assistant trying to run student's homework assignments. Therefore the TA may not have intimate knowledge of the circuits being run

**Comment by ahirthucla** [comment] 2021-03-23 18:47
**My Experience**
When submitting many circuits to [run_batch](https://github.com/quantumlib/Cirq/blob/c27dcffcab6a62540bd939fb05055fabd474a1a1/cirq/google/engine/engine.py#L300), two runtime errors occurred. 

The run_batch function would properly complete, but the Google Quantum Computing Service would mark the job with either (INVALID_PROGRAM, Program too long) or (INVALID_PROGRAM, Duplicate measurement key: _measurement key_). 

- The former error is caused by a single one of the circuits in the batch having too long of a runtime. The only documentation I'm aware of that covers this limitation is [here](https://quantumai.google/cirq/google/devices#general_limitations). 
- I discovered on my own that the latter error is caused by **different circuits** in the same batch having the same measurement keys. I'm not sure if this is covered in any documentation somewhere. 

In both of these cases, the entire batch errors, even if only one or two circuits were the problem. This is problematic in the situation where you want to run many circuits, as you have no (or little) way of knowing which circuit caused the issue. 

**Workarounds**
- For the 'Program too long' error, I set a hard limit on the number of operations that a student's circuit could have and be validated to run in the next cycle. I selected this limit by hand, and tuned it manually until the 'Program too long' error stopped happening as frequently. 
- For the 'Duplicate measurement keys' error, considered workarounds include adding unique values to the measurement keys of the circuits of a batch (rudimentary implementation), and separating circuits with duplicate keys into different batches (unimplemented). 
- For both errors, if a circuit is in a batch that fails, it is marked as "unbatchable", and run once again, by itself. This way the erroring circuit will fail, while the other circuits in that batch will succeed. 

**Desired Solution**
This solution is threefold: 
1. **device.validate_circuit()**: For the device provided by [cirq.google.get_engine_device()](https://quantumai.google/reference/python/cirq/google/get_engine_device), if a circuit passes device.validate_circuit(), then it should be guaranteed to pass all of the pre-run checks in the Quantum Computing Service system. This should allow one to check for the 'Program too long' error before submitting the circuit in a batch or otherwise. 
2. **engine.validate_batch()**: For the engine provided by [cirq.google.get_engine()](https://quantumai.google/reference/python/cirq/google/Engine), if a batch of circuits passes engine.validate_batch(), then it should pass the pre-run checks, like before. This should allow one to check for 'Duplicate measurement key' errors before submitting the batch. 
3. **cirq.google.optimized_for_sycamore()**: This should call device.validate_circuit() somewhere towards the end. If a circuit is successfully optimized by this function, then it should be valid to run on the device it was optimized for. 

**Urgency**
I want to say ASAP, for any other classes or groups who may have a similar use case to ours, but the next time we'll teach this class is in 9 months, so we'd greatly appreciate these improvements at least by then.

**Comment by mpharrigan** [comment] 2021-05-27 18:54
related? https://github.com/quantumlib/Cirq/issues/3244

**Comment by balopat** [comment] 2021-05-27 19:14
> related? #3244

Could be but doesn't sound like it, as the recommended solution is not about changing the interface - but instead the Engine implementation of it.

1. It sounds like a size check is something that could be part of the validation routine 
2. Duplicate measurement key is something that is really odd and we should look at - but again not part of the device hierarchy/interface design necessarily 
3. Maybe if we could align device transpilers with device validation better, we could somehow force this validation - but I'm not sure I agree with this coupling as it is relatively easy for a user to call the transpiler and then the validator after each other.

**Comment by mpharrigan** [comment] 2021-06-09 00:01
What about validating gates used and qubits used?

**Comment by dstrain115** [comment] 2022-01-28 02:33
This can now be done by the virtual engine factory and the resulting validation.  File any limitations against that component.

https://github.com/quantumlib/Cirq/blob/master/cirq-google/cirq_google/engine/virtual_engine_factory.py

**Closed by dstrain115** 2022-01-28 02:33 UTC
Labels: kind/feature-request, triage/accepted, area/google, area/google/engine, area/batching, priority/p1-urgent, google-EAP
