### ISSUE TITLE
Circuit currently allows measure gates with duplicated keys. Is this intentional?

### ISSUE THREAD

**Issue by zchen088** [quantumlib/Cirq#2409] opened 2019-10-25 21:24 UTC

**Comment by vtomole** [comment] 2019-10-28 16:32
It's not intentional. We are trying to get https://github.com/quantumlib/Cirq/pull/1862 in. Closing as a duplicate of https://github.com/quantumlib/Cirq/issues/2152.

**Closed by vtomole** 2019-10-28 16:32 UTC
